# -*- coding: utf-8 -*-
"""Shopifystocks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCbyLUiBxpiUb6__artyHD7kJJ04qID6
"""

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/Shopify.csv"

import pandas as pd
df = pd.read_csv(file_path)
df.head()

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns)
print("\nData Types:")
print(df.dtypes)
print("\nFirst 5 Rows:")
display(df.head())

print(df.isnull().sum())

price_columns = ['Open', 'High', 'Low', 'Close', 'Volume']
for column in price_columns:
    df[column] = pd.to_numeric(df[column], errors='coerce')

df = df.dropna(subset=price_columns)

df['Date'] = pd.to_datetime(df['Date'], errors='coerce', utc=True)
df = df.dropna(subset=['Date'])
df = df.sort_values('Date')
df = df.reset_index(drop=True)
df.head()

df['Daily_Delta'] = df['Close'] - df['Open']

print(df[['Date', 'Open', 'Close', 'Daily_Delta']].head())

df['Daily_Return'] = df['Close'].pct_change() * 100

print(df[['Date', 'Open', 'Close', 'Daily_Delta', 'Daily_Return']].head())

print(df[['Date', 'Close', 'Daily_Return']].head())

print(df.columns.tolist())

average_volume = df['Volume'].mean()
print("Average Trading Volume:", average_volume)

df['Volume_MA_20'] = df['Volume'].rolling(20).mean()
print(df[['Date', 'Volume', 'Volume_MA_20']].head(25))

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.plot(df['Date'], df['Volume'], label='Daily Volume')
plt.plot(df['Date'], df['Volume_MA_20'], label='20-Day Average Volume')

plt.title('Shopify Trading Volume Trend')
plt.xlabel('Date')
plt.ylabel('Trading Volume')

plt.legend()
plt.grid()

plt.show()

import pandas as pd
import os

# Automatically reconstruct df if it was cleared from memory
if 'df' not in globals():
    file_path = "/content/drive/MyDrive/Shopify.csv"
    if os.path.exists(file_path):
        df = pd.read_csv(file_path)
    else:
        raise FileNotFoundError(f"Variable 'df' is missing and file not found at {file_path}. Please mount Google Drive.")

volume_mean = df['Volume'].mean()
volume_std = df['Volume'].std()

print("Average Trading Volume:", volume_mean)
print("Volume Standard Deviation:", volume_std)

high_volume_days = df[
    df['Volume'] > volume_mean + 2 * volume_std
]

print("Anomalous Trading Days:")

display(
    high_volume_days[
        ['Date', 'Close', 'Volume']
    ]
)

print("Number of Anomalous Trading Days:", len(high_volume_days))

returns = df['Daily_Return'].dropna()

print("Mean Return:", returns.mean())
print("Variance:", returns.var())
print("Standard Deviation:", returns.std())

print(df['Daily_Return'].describe())

plt.figure(figsize=(10, 5))

plt.hist(
    df['Daily_Return'].dropna(),
    bins=50
)

plt.title('Shopify Daily Return Distribution')
plt.xlabel('Daily Return (%)')
plt.ylabel('Frequency')

plt.grid()

plt.show()

print("Final Dataset:")

display(df.head())

print("Final Dataset:")

display(df.head())

print("Missing Values:")

print(df.isnull().sum())